//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunerariaMuertoFeliz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta
    {
        public int idboleta { get; set; }
        public int plan_id { get; set; }
        public int usuario_id { get; set; }
        public int pago_id { get; set; }
        public System.DateTime created_at { get; set; }
        public int parque_id { get; set; }
        public System.DateTime fechaFuneral { get; set; }
        public int fallecido_id { get; set; }
        public List<pago> listapago { get; set; }
    
        public virtual boleta boleta1 { get; set; }
        public virtual boleta boleta2 { get; set; }
        public virtual fallecido fallecido { get; set; }
        public virtual pago pago { get; set; }
        public virtual parque parque { get; set; }
        public virtual planes planes { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
