//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunerariaMuertoFeliz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FunerariaEntities : DbContext
    {
        public FunerariaEntities()
            : base("name=FunerariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boleta> boleta { get; set; }
        public virtual DbSet<fallecido> fallecido { get; set; }
        public virtual DbSet<pago> pago { get; set; }
        public virtual DbSet<parque> parque { get; set; }
        public virtual DbSet<planes> planes { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipoplan> tipoplan { get; set; }
        public virtual DbSet<tipousuario> tipousuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
