//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunerariaMuertoFeliz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class planes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public planes()
        {
            this.boleta = new HashSet<boleta>();
        }
    
        public int idplanes { get; set; }
        public string nombre { get; set; }
        public string primer_contenido { get; set; }
        public string segundo_contenido { get; set; }
        public string tercer_contenido { get; set; }
        public string cuarto_contenido { get; set; }
        public string quinto_contenido { get; set; }
        [DisplayFormat(DataFormatString = "{0:C3}")]
        public decimal precio { get; set; }
        public int tipoplan_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleta> boleta { get; set; }
        public virtual tipoplan tipoplan { get; set; }
    }
}
