//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunerariaMuertoFeliz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.boleta = new HashSet<boleta>();
        }
    
        public int idusuario { get; set; }
        [ScaffoldColumn(false)]
        [Required(ErrorMessage = "Nombre requerido")]
        [StringLength(45)]
        public string nombre { get; set; }
        [ScaffoldColumn(false)]
        [Required(ErrorMessage = "Apellido Paterno requerido")]
        [StringLength(45)]
        public string apellidoP { get; set; }
        [ScaffoldColumn(false)]
        [Required(ErrorMessage = "Apellido Materno requerido")]
        [StringLength(45)]
        public string apellidoM { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string pass { get; set; }
        public int tipousuario_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleta> boleta { get; set; }
        public virtual tipousuario tipousuario { get; set; }
    }
}
